#!/bin/bash
# This is the installation script for all the software used for Manjaro

aur() {
  if [[ -z $1 ]]; then
    echo "At least one package must be provided"
  else
    for var in "$@"
    do
      aur_download "$var"
    done
  fi
}

aur_download () {
  if [ -z $1 ]; then
    echo "AUR package name must be provided"
  else
    AUR="https://aur.archlinux.org/$1.git"
    git clone $AUR
    cd $1
    makepkg -sic --noconfirm
    cd ..
    sudo rm -rf $1
  fi
}

# Update packages first to prevent errors
echo "Updating system..."
sudo pacman -Syy --noconfirm
sudo pacman -Su --noconfirm

# Install all applications compatible with pacman
# Install essential packages
echo "Installing essential packages..."
sudo pacman -S --noconfirm base-devel gcc make linux$(uname -r|sed 's/\W//g'|cut -c1-3)-headers

# Install both Java 8 and 11 - use Java 11 as default while Java 8 is used for development purposes
echo "Installing Java 8 & 11 and set Java 11 as default"
sudo pacman -S --noconfirm jre8-openjdk jdk8-openjdk openjdk8-doc jre11-openjdk jdk11-openjdk openjdk11-doc
sudo archlinux-java set java-11-openjdk

# Install all the basic applications
echo "Installing basic application"
sudo pacman -S --noconfirm vim telegram-desktop libreoffice-still gimp noto-fonts-emoji discord xclip neofetch pandoc python-pip noto-fonts-cjk expect alacritty

# Set up Docker (Sets the docker service to run on boot too)
echo "Installing Docker"
sudo pacman -S --noconfirm docker docker-machine docker-compose
sudo systemctl start docker
sudo systemctl enable docker
sudo gpasswd -a $USERNAME docker

# Installing emacs + spacemacs
echo "Installing spacemacs and loading configuration"
sudo pacman -S --noconfirm emac
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
cp -f ~/dotfiles/emacs/.spacemacs ~/.spacemacs

# Install VirtualBox
echo "Installing VirtaulBox"
uname -r
pacman -S virtualbox
gpassword -a $USERNAME vboxusers

# Install all applicatons found in the AUR
echo "Installing AUR packages"
aur "yay" "google-chrome" "jetbrains-toolbox" "visual-studio-code-bin" "postman" "heroku-cli"

echo "Clearing unused packages"
sudo pacman -Rcns --noconfirm firefox

# Copy code snippets folder to home
echo "Adding code snippets"
cp -r ~/dotfiles/snippets/ ~/

# Reboot OS
sudo reboot
