#!/bin/bash
# List of general commands - to be loaded on shell start

# Detailed ls command
alias ls="ls -la --color"

# Launch VS Code with scale factor forced
alias code="code --force-device-scaled-factor=1.2"

# Syncs .zshrc to reload the utility scripts available
alias sync="source ~/.zshrc"

# Clears contents of a folder
alias clear-folder="rm -rf ./*"

# Use pandoc to convert all Markdown files in a folder to org files
function md-to-org {
  for f in ./*.md; do
    name=$(basename $f .md)
    pandoc -f markdown -t org -o $name.org ${f}
  done
}

# Create a new directory and cd into it
function newdir {
  mkdir $1
  cd $1
}

# Sync all dotfiles
function dsync {
  cp ~/.spacemacs ~/dotfiles/emacs/.spacemacs
  cp ~/.zshrc ~/dotfiles/.zshrc

  cp -r ~/snippets ~/dotfiles/
}
