#!/bin/bash
# List of general commands - to be loaded on shell start

function reve {
  echo $1|rev
}

alias sharpen="xrandr --output DP1 --auto"

alias c="clear"

# Detailed ls command
alias ls="ls -lA --color"

# Syncs .zshrc to reload the utility scripts available
alias sync="source ~/.zshrc"

# Clears contents of a folder
alias clear-folder="rm -rf ./*"

alias bkup="~/IdeaProjects/backtup/build/install/backtup/bin/backtup"

alias project-screen="intel-virtual-output"

alias open="ranger"

alias yay="yay --color=auto"

alias sysupdate="yay -Syyu"

alias rollback="pacman -Suu"

alias tldr="tldr -t ocean"

alias rr="curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash"

alias upwatch="sudo sysctl -p"

alias uxplay="/usr/local/bin/uxplay"

# Restart plasmashell
alias rps="killall plasmashell && kstart5 plasmashell &> /dev/null"

# Remove alias for Ghostscript and remap to gst
alias gs="gst"

# Exports a markdown file to pdf using pandoc
function convert {
  TARGET=$([[ -z "$1" ]] && echo 'README.md' || echo "$1")
  DESTINATION=$([[ -z "$2" ]] && echo 'README.pdf' || echo "$2")

  echo "Exporting $TARGET to $DESTINATION"

  if [[ ! -f "float-adjustment.tex" ]]; then
    echo '\\usepackage{float}' > float-adjustment.tex
    echo '\\floatplacement{figure}{H}' >> float-adjustment.tex
  fi

  pandoc $TARGET --toc -V linkcolor:blue -H float-adjustment.tex -o $DESTINATION

  rm float-adjustment.tex
}

# Use pandoc to convert all Markdown files in a folder to org files
function md-to-org {
  for f in ./*.md; do
    local name=$(basename $f .md)
    pandoc -f markdown -t org -o $name.org ${f}
  done
}

# Create a new directory and cd into it
function mkcd {
  mkdir $1
  cd $1
}

# Sync all dotfiles
function dsync {
  cp ~/.zshrc ~/dotfiles/.zshrc
  cp ~/.ideavimrc ~/dotfiles/.ideavimrc
  cp ~/.vimrc ~/dotfiles/.vimrc
  cp ~/.config/nvim/init.vim

  cp -r ~/.config/fontconfig/ ~/dotfiles/fontconfig/
}
