#!/bin/bash
# Git commands - to be added on shell start

# Display detailed version of git log
alias log="git log --oneline --graph"

# Quickly clone a project
# Accepts Git user (1) and project name (2) as arguments
function clone {
  user=$1
  project=$2

  if [[ -z $user || -z $project ]]; then
    echo "Must provide Git user and project name"
    return 1
  fi

  git clone git@github.com:$user/$project.git
  cd $project
}

# Display status of repository
alias status="git status"

# Checkout a new branch
function checkout {
  git checkout -b $1
}

# Merges master/origin and deletes local branch
function merge-branch {
  git checkout master
  git fetch origin master
  git merge origin/master
  git branch -d "$1"
}
