#!/bin/bash
# Git commands - to be added on shell start

# Display detailed version of git log
alias log="git log --oneline --graph"

# Quickly clone a project
alias clone="git clone"

# Display status of repository
alias status="git status"

# Checkout a new branch
function checkout {
  git checkout -b $1
}

# Merges master/origin and deletes local branch
function merge-branch {
  git checkout master
  git fetch origin master
  git merge origin/master
  git branch -d "$1"
}
