#!/bin/bash
# Racket commands - to be added on shell start

# Create new racket source file
function newrkt {
  local racket_file="$1.rkt"
  touch "$racket_file"
  echo "#!/usr/bin/racket" >> $racket_file
  echo "#lang racket" >> $racket_file
}
